const pagesData = [
  {
    title: "IT Support",
    imageUrl: "../../assets/img/course/01-ba-it.jpg",
    credits: 120,
    length: "3 YEARS",
    description: [
      "<div>This course provides students with the knowledge and skills required to troubleshoot, maintain, and repair computer systems, networks, and software applications. Students will learn to identify and resolve common IT issues, configure and manage network devices, and provide excellent customer service as an IT support specialist.</div>",

      "<div class='mb-1, mt-4'><b>Course Objectives:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Identify and troubleshoot common hardware and software issues</li>",
      "<li style='list-style-type: disc' class='ms-3'>Configure and manage network devices and protocols</li>",
      "<li style='list-style-type: disc' class='ms-3'>Install, configure, and manage operating systems and software applications</li>",
      "<li style='list-style-type: disc' class='ms-3'>Provide excellent customer service and support</li>",
      "<li style='list-style-type: disc' class='ms-3'>Understand IT security best practices and risk management</li>",
      "<li style='list-style-type: disc' class='ms-3'>Develop problem-solving and critical thinking skills</li>",

      "<div class='mb-1, mt-4'><b>Year 1:</b></div>",
      "<div class='mb-1'><b>Semester 1:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Introduction to Computer Systems</li>",
      "<li style='list-style-type: disc' class='ms-3'>Networking Fundamentals</li>",
      "<li style='list-style-type: disc' class='ms-3'>IT Support Principles</li>",
      "<li style='list-style-type: disc' class='ms-3'>Computer Hardware and Troubleshooting</li>",

      "<div class='mb-1, mt-4'><b>Semester 2:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Operating Systems (Windows, macOS, Linux)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Software Applications and Troubleshooting</li>",
      "<li style='list-style-type: disc' class='ms-3'>Network Protocols and Security</li>",
      "<li style='list-style-type: disc' class='ms-3'>Help Desk Management</li>",

      "<div class='mb-1, mt-4'><b>Year 2:</b></div>",
      "<div class='mb-1'><b>Semester 1:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Advanced Networking (TCP/IP, DNS, DHCP)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Server Administration (Windows, Linux)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Database Management (MySQL, SQL)</li>",
      "<li style='list-style-type: disc' class='ms-3'>IT Project Management</li>",

      "<div class='mb-1, mt-4'><b>Semester 2:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Advanced Operating Systems (Virtualization, Cloud Computing)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Network Security and Threat Management</li>",
      "<li style='list-style-type: disc' class='ms-3'>IT Service Management (ITIL)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Web Development (HTML, CSS, JavaScript)</li>",

      "<div class='mb-1, mt-4'><b>Year 3:</b></div>",
      "<div class='mb-1'><b>Semester 1:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Advanced IT Support (Troubleshooting, Problem-Solving)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Cloud Computing (AWS, Azure, Google Cloud)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Cybersecurity (Threat Analysis, Incident Response)</li>",
      "<li style='list-style-type: disc' class='ms-3'>IT Research Methods</li>",

      "<div class='mb-1, mt-4'><b>Semester 2:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Capstone Project (IT Support)</li>",
      "<li style='list-style-type: disc' class='ms-3'>Electives (Choose one: Data Analytics, Artificial Intelligence, Internet of Things)</li>",

      "<div class='mb-1, mt-4'><b>Electives:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Data Analytics</li>",
      "<li style='list-style-type: disc' class='ms-3'>Artificial Intelligence</li>",
      "<li style='list-style-type: disc' class='ms-3'>Internet of Things</li>",
      "<li style='list-style-type: disc' class='ms-3'>Advanced Cybersecurity</li>",
      "<li style='list-style-type: disc' class='ms-3'>IT Entrepreneurship</li>",

      "<div class='mb-1, mt-4'><b>Assessment:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>Exams</li>",
      "<li style='list-style-type: disc' class='ms-3'>Assignments</li>",
      "<li style='list-style-type: disc' class='ms-3'>Projects</li>",
      "<li style='list-style-type: disc' class='ms-3'>Quizes</li>",
      "<li style='list-style-type: disc' class='ms-3'>Final year project (Capstone)</li>",

      "<div class='mb-1, mt-4'><b>Career Opportunities:</b></div>",
      "<li style='list-style-type: disc' class='ms-3'>IT Support Specialist</li>",
      "<li style='list-style-type: disc' class='ms-3'>Help Desk Technician</li>",
      "<li style='list-style-type: disc' class='ms-3'>Network Administrator</li>",
      "<li style='list-style-type: disc' class='ms-3'>Server Administrator</li>",
      "<li style='list-style-type: disc' class='ms-3'>Cybersecurity Specialist</li>",
      "<li style='list-style-type: disc' class='ms-3'>IT Project Manager</li>",
      "<li style='list-style-type: disc' class='ms-3'>Cloud Computing Professional</li>",
    ],
    professorImg: "../../assets/img/team/logo.png", // Update the professor image URL as needed
    professorName: "HBIU", // Update the professor name as needed
    category: "IT Support",
    enrolled: 106,
    courseTime: "3 Years",
    courseFees: "$20,000",
    lectures: 4,
    quizes: " ",
    duration: "3 Years",
    language: "English",
    skillLevel: "Intermediate",
    location: "Online/On Campus" + "/" + "On Campus",
    students: 105,
    certificate: "Yes",
    assessments: "Yes",
  },
];
